import axios from "axios";

// const url = "https://khwanta56-zfn2h52c7a-uc.a.run.app";
const url = "http://localhost:8080";
export const createPost = (newPost) => axios.post(url, newPost);
export const likePost = (id) => axios.patch(`${url}/${id}/likePost`);
export const updatePost = (id, updatedPost) => axios.patch(`${url}/${id}`, updatedPost);
export const deletePost = (id) => axios.delete(`${url}/${id}`);

export const getType = () => axios.get(`${url}/gettype`);
export const getProductCategory = () => axios.get(`${url}/getProductCategory`);
export const getBrand = () => axios.get(`${url}/getbrand`);
export const getPattern = () => axios.get(`${url}/getpattern`);
export const getFabricType = () => axios.get(`${url}/getfabrictype`);
export const getSize = () => axios.get(`${url}/getsize`);
export const getSizeDe = () => axios.get(`${url}/getsizede`);
export const getProduct = (page) => axios.get(`${url}/getproduct?page=${page}`);
export const getProductBysearch = (searchQuery) => axios.get(`${url}/getproduct/search?searchQuery=${searchQuery.searchBar}`);
export const getWarehouse = () => axios.get(`${url}/getwarehouse`);
export const getSingleProduct = (id) => axios.get(`${url}/getproducts/${id}`);
export const addPetern = (newPattern) => axios.post(`${url}/addpettern`, newPattern);
export const addType = (newType) => axios.post(`${url}/addtype`, newType);
export const addFabric = (newFabric) => axios.post(`${url}/addFabric`, newFabric);
export const addproduct = (newProduct) => axios.post(`${url}/addproduct`, newProduct);
export const addDesign = (newDesign) => axios.post(`${url}/adddesign`, newDesign);
export const addKhwantaProduct = (newdata) => axios.post(`${url}/addKhwantaProduct`, newdata);
export const getDesignCode = () => axios.get(`${url}/getdesigncode`);
export const getViewDesign = (page) => axios.get(`${url}/getviewdesign?page=${page}`);
export const getSingleDesign = (id) => axios.get(`${url}/getdesign/${id}`);
export const getPrintstockBarcode = () => axios.get(`${url}/getproductstock`);
export const Delproduct = (id) => axios.delete(`${url}/delproducts/${id}`);
export const getAddDesign = () => axios.get(`${url}/getadddesign`);